### ISSUE TITLE
Elk config failing on agent deployment

### ISSUE THREAD

**Issue by Davewarrington** [Orange-Cyberdefense/GOAD#16] opened 2022-07-13 08:38 UTC
Post ansible config of the server i circled back to configure elk, however it fails when checking if chocolatey is installed, with the following  error

fatal: [192.168.56.11]: FAILED! => {"changed": false, "command": "C:\\ProgramData\\chocolatey\\bin\\choco.exe install chocolatey-core.extension --fail-on-unfound --yes --no-progress --limit-output --timeout 2700", "msg": "Error installing package(s) 'chocolatey-core.extension'", "rc": 1, "stderr": "", "stderr_lines": [], "stdout": "Installing the following packages:\r\nchocolatey-core.extension\r\nBy installing, you accept licenses for the packages.\r\nchocolatey-core.extension not installed. An error occurred during installation:\r\n The remote server returned an error: (429) Too Many Requests. Too Many Requests\r\nchocolatey-core.extension package files install failed with exit code 1. Performing other installation steps.\r\nThe install of chocolatey-core.extension was NOT successful.\r\nchocolatey-core.extension not installed. An error occurred during installation:\r\n The remote server returned an error: (429) Too Many Requests. Too Many Requests\r\n\r\nChocolatey installed 0/1 packages. 1 packages failed.\r\n See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log).\r\n\r\nFailures\r\n - chocolatey-core.extension (exited 1) - chocolatey-core.extension not installed. An error occurred during installation:\r\n The remote server returned an error: (429) Too Many Requests. Too Many Requests\r\n", "stdout_lines": ["Installing the following packages:", "chocolatey-core.extension", "By installing, you accept licenses for the packages.", "chocolatey-core.extension not installed. An error occurred during installation:", " The remote server returned an error: (429) Too Many Requests. Too Many Requests", "chocolatey-core.extension package files install failed with exit code 1. Performing other installation steps.", "The install of chocolatey-core.extension was NOT successful.", "chocolatey-core.extension not installed. An error occurred during installation:", " The remote server returned an error: (429) Too Many Requests. Too Many Requests", "", "Chocolatey installed 0/1 packages. 1 packages failed.", " See the log for details (C:\\ProgramData\\chocolatey\\logs\\chocolatey.log).", "", "Failures", " - chocolatey-core.extension (exited 1) - chocolatey-core.extension not installed. An error occurred during installation:", " The remote server returned an error: (429) Too Many Requests. Too Many Requests"]}

It does how ever appear to work on SRV03 !

**Comment by Davewarrington** [comment] 2022-07-13 08:42
ahh, you need to also un comment the elk section in the Hosts.yml file also

**Comment by Davewarrington** [comment] 2022-07-13 08:56
Ran in to this error after .. 

fatal: [192.168.56.50]: FAILED! => {"cache_update_time": 1639938438, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'apt-transport-https' 'gnupg2'' failed: E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/g/gnupg2/gnupg2_2.2.4-1ubuntu1.4_all.deb  404  Not Found [IP: 185.125.190.39 80]\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "rc": 100, "stderr": "E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/g/gnupg2/gnupg2_2.2.4-1ubuntu1.4_all.deb  404  Not Found [IP: 185.125.190.39 80]\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "stderr_lines": ["E: Failed to fetch http://archive.ubuntu.com/ubuntu/pool/universe/g/gnupg2/gnupg2_2.2.4-1ubuntu1.4_all.deb  404  Not Found [IP: 185.125.190.39 80]", "E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following NEW packages will be installed:\n  apt-transport-https gnupg2\n0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.\nNeed to get 5,292 B/9,640 B of archives.\nAfter this operation, 206 kB of additional disk space will be used.\nIgn:1 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 gnupg2 all 2.2.4-1ubuntu1.4\nErr:1 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 gnupg2 all 2.2.4-1ubuntu1.4\n  404  Not Found [IP: 185.125.190.39 80]\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following NEW packages will be installed:", "  apt-transport-https gnupg2", "0 upgraded, 2 newly installed, 0 to remove and 0 not upgraded.", "Need to get 5,292 B/9,640 B of archives.", "After this operation, 206 kB of additional disk space will be used.", "Ign:1 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 gnupg2 all 2.2.4-1ubuntu1.4", "Err:1 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 gnupg2 all 2.2.4-1ubuntu1.4", "  404  Not Found [IP: 185.125.190.39 80]"]}

Resolve it by  One time login to the elk box via ssh.

**Comment by Mayfly277** [comment] 2022-07-19 22:34
I will do some tests on elk to see if i can reproduce.
Thx for the feedback.

**Comment by q-mallet** [comment] 2022-09-18 10:59
Same issue !
apt update && apt upgrade -y works for me.

**Comment by Mayfly277** [comment] 2022-10-04 07:47
fixed in pr #53

**Closed by Mayfly277** 2022-10-04 07:47 UTC
