### ISSUE TITLE
No MSFT_NetAdapter objects found with property 'Name' equal to 'Ethernet'

### ISSUE THREAD

**Issue by NeffIsBack** [Orange-Cyberdefense/GOAD#106] opened 2023-06-07 14:22 UTC
Hi, 
first of all thanks for the really great proxmox setup guide!

During the ansible provisioning i ran into the error message
``` 
TASK [common : Force a DNS on the adapter Ethernet] ***********
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ScriptStackTrace:
fatal: [srv03]: FAILED! => {"changed": false, "msg": "Unhandled exception while executing module: No MSFT_NetAdapter objects found with property 'Name' equal to 'Ethernet'.  Verify the value of the property and retry."}
```

This error occured because somehow the network adapters were named "Ethernet 2" after my setup. To solve the issue i simply changed the `net_adapter` and `domain_adapter` value from `Ethernet` to `Ethernet*`. I have no idea why the ethernet adapters got named them "Ethernet 2" (there is no other ethernet adapter) but maybe this is still an easy fix to implement. 

I also got some minor problems when following the proxmox guide, but they were more of a lack-of-knowledge kind, than issues with the actual code. But tell me if you are still interested in feedback :)

**Comment by HarunYasin** [comment] 2023-10-30 17:41
Hi NeffIsBack,
where and how did you changed the values from the adapters? Do you need credentials for performing this?
Best regards
Harry

**Comment by NeffIsBack** [comment] 2023-10-30 18:16
When you cloned the repository you should be able to find the lines with the network adapter configuration here:

https://github.com/Orange-Cyberdefense/GOAD/blob/e875942c6a840ecd88b06ad6e19fc823a7f028e2/ad/NHA/providers/proxmox/inventory_disablevagrant#L21

Depending on the provider the path is different, I used proxmox.

**Comment by HarunYasin** [comment] 2023-10-30 19:03
Thank you! I was on hurry. Seems to escaped from me. I am also deploying on Proxmox. Cheers.

**Comment by mubix** [comment] 2023-11-25 02:11
Had the same issue and updated the inventory file to say `Ethernet 2` fixed it. I have no clue why it names it that way either. There are methods to get the first ethernet device or an ethernet device with a specific IP address. Hopefully I can find some time to update the ansible scripts to pull that info out.

**Comment by jamu85** [comment] 2024-01-04 04:49
> Had the same issue and updated the inventory file to say `Ethernet 2` fixed it. I have no clue why it names it that way either. There are methods to get the first ethernet device or an ethernet device with a specific IP address. Hopefully I can find some time to update the ansible scripts to pull that info out.

https://github.com/Orange-Cyberdefense/GOAD/issues/107#issuecomment-1876306698

**Comment by Mayfly277** [comment] 2024-03-25 13:25
duplicate of #107 i will change it to Ethernet 2 by default for proxmox.

**Closed by Mayfly277** 2024-03-25 13:25 UTC
