### ISSUE TITLE
An error occurred executing a remote WinRM command.

### ISSUE THREAD

**Issue by thomas-girard** [Orange-Cyberdefense/GOAD#88] opened 2023-02-20 12:29 UTC
This problem appears when you run "vagrant up" for the installation on a machine under arch linux. 
![image](https://user-images.githubusercontent.com/70712826/220107848-b4c1b9d7-b126-4c40-aad6-a71c43969fce.png)

**Comment by Mayfly277** [comment] 2023-02-20 20:23
Hello,
Duplicate of this : https://github.com/Orange-Cyberdefense/GOAD/issues/17
and this : https://github.com/Orange-Cyberdefense/GOAD/issues/11

You should take a look at this : https://github.com/Orange-Cyberdefense/GOAD/issues/11#issuecomment-1179544501
Or you can also downgrade vagrant : https://github.com/Orange-Cyberdefense/GOAD/issues/11#issuecomment-1189646477

**Closed** 2023-02-21 15:28 UTC
