### ISSUE TITLE
{"changed": true, "msg": "failed to join domain: Computer 'castelblack' failed to join domain 'north.sevenkingdoms.local'

### ISSUE THREAD

**Issue by Argonx21** [Orange-Cyberdefense/GOAD#266] opened 2024-08-18 08:28 UTC
I am facing the below issue during the installation process. Can anyone suggest a possible fix for this issue?

```bash
fatal: [srv02]: FAILED! => {"changed": true, "msg": "failed to join domain: Computer 'castelblack' failed to join domain 'north.sevenkingdoms.local' from its current workgroup 'WORKGROUP' with following error message: The specified domain either does not exist or could not be contacted.", "reboot_required": false}
```

**Comment by mueller** [comment] 2024-09-08 18:11
I got the same problem. At first I tried adding `north.sevenkingdoms.local` manually to the `hosts` file and re-running the `goad.sh` script (as suggested in https://github.com/Orange-Cyberdefense/GOAD/issues/97#issuecomment-1693988273).

However, that didn't work and it seems like the root cause is that the north domain is not created:

![image](https://github.com/user-attachments/assets/2b3435d6-27de-4f6f-8b5d-da15f291ee63)

**Comment by CalfCrusher** [comment] 2024-09-25 19:20
Same problem here

**Comment by shoxxdj** [comment] 2024-10-12 15:24
Same here :/

**Comment by Thangart** [comment] 2024-10-14 11:00
Check. i got the same problem. looks like DC02 lost all its connection with the parent DC and demotes. I'll have a look at it once i have some more spare time

**Comment by Thangart** [comment] 2024-10-15 10:13
Hmm it looks like the NAT interface is interfering with setting up the north domain.
Curiously by looking at the ansible config to set up the child domain in the file: "ansible/roles/child_domain/tasks/main.yml"  we cna see that there are some commented out blocks at line 27 and 87 that refer to disabling the NAT interface and enabling it  later in the playbook. 

![Screenshot_20241015_120406](https://github.com/user-attachments/assets/bea616f3-7ed5-45d1-af38-5536289c6669)


![Screenshot_20241015_120415](https://github.com/user-attachments/assets/6395432f-b99e-416d-a2ea-902b2dff2386)

Reenabling this code by removing the # and 2 spaces, and running the install gives me a working "north." subdomain and continues the installation as it should.

Just for quick reference. Which provider are you using and which version of it? For me it was Virtualbox version 7.1.2

**Comment by shoxxdj** [comment] 2024-10-16 16:14
Finally works like a charm with @Thangart tips.

I'm using virtualbox 7.1.4-1

**Comment by mueller** [comment] 2024-10-17 12:06
> Reenabling this code by removing the # and 1 space, and running the install gives me a working "north." subdomain and continues the installation as it should.

Worked for me as well, thank you very much! :slightly_smiling_face:

**Comment by Mayfly277** [comment] 2024-10-20 22:37
subdomain dns issues should have been fixed now in v3, so i close.

**Closed by Mayfly277** 2024-10-20 22:37 UTC
