### ISSUE TITLE
WinRM Authentication Failure

### ISSUE THREAD

**Issue by PerennaSec** [Orange-Cyberdefense/GOAD#138] opened 2023-11-05 16:39 UTC
When running the install script, WinRM reports an authentication failure. Although the error message says to increase the `vm.boot.timeout` parameter, I don't feel this is the issue as the ten minute timeout in the Vagrantfile should be plenty. My suspicion is that it's somehow related to the IP address of the host-only network `vboxnet0`, which I have configured in the `192.168.56.101/24` range. 

Running `vagrant up` with `--debug` gives the following: 

`DEBUG winrmshell: [WinRM] opening remote shell on http://127.0.0.1:55985/wsman`

Whereas the Vagrantfile shows client IP's should be in the `192.168.56.10/24` range. I could be barking up the wrong tree; I've been trying to troubleshoot this for the past day or so and I am admittedly out of ideas. I would deeply appreciate some help, I love this project and I can't wait to get it to run!

Relevant debug output is as follows:

```
3931   │ DEBUG winrmshell: [WinRM] opening remote shell on http://127.0.0.1:55985/wsman
3932   │  INFO winrm: WinRM not ready: #<VagrantPlugins::CommunicatorWinRM::Errors::AuthenticationFaile
       │ d: An authorization error occurred while connecting to WinRM.

```

```
3934   │ User: vagrant
3935   │ Endpoint: http://127.0.0.1:55985/wsman
3936   │ Message: WinRM::WinRMAuthorizationError>
3937   │  INFO interface: detail: Warning: Authentication failure. Retrying...
3938   │  INFO interface: detail:     DC01: Warning: Authentication failure. Retrying...
3939   │     DC01: Warning: Authentication failure. Retrying...
3940   │  INFO winrm: Checking whether WinRM is ready...
3941   │ DEBUG provider: Searching for cap: winrm_info
3942   │ DEBUG provider: Checking in: virtualbox
3943   │  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "93d208e2-fbf7-4071-
       │ b49d-b4e93ee70468", "--machinereadable"]
3944   │  INFO subprocess: Command not in installer, restoring original environment...
3945   │ DEBUG subprocess: Selecting on IO
3946   │ DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
3947   │ DEBUG subprocess: Exit status: 0
3948   │ DEBUG virtualbox_7_0: Searching for SSH port: 22
3949   │ DEBUG virtualbox_7_0: read_forward_ports: uuid=93d208e2-fbf7-4071-b49d-b4e93ee70468 active_onl
       │ y=false
3950   │  INFO subprocess: Starting process: ["/usr/bin/VBoxManage", "showvminfo", "93d208e2-fbf7-4071-
       │ b49d-b4e93ee70468", "--machinereadable"]
3951   │  INFO subprocess: Command not in installer, restoring original environment...
3952   │ DEBUG subprocess: Selecting on IO
3953   │ DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
3954   │ DEBUG subprocess: Exit status: 0
3955   │ DEBUG virtualbox_7_0:   - [1, "ssh", 2222, 22, ""]
3956   │ DEBUG virtualbox_7_0:   - [1, "winrm", 55985, 5985, "127.0.0.1"]
3957   │ DEBUG virtualbox_7_0:   - [1, "winrm-ssl", 55986, 5986, "127.0.0.1"]
3958   │ DEBUG ssh: Checking key permissions: /home/theseus/.vagrant.d/insecure_private_keys/vagrant.ke
       │ y.ed25519
3959   │ DEBUG ssh: Checking key permissions: /home/theseus/.vagrant.d/insecure_private_keys/vagrant.ke
       │ y.rsa
3960   │ DEBUG provider: Searching for cap: forwarded_ports
3961   │ DEBUG provider: Checking in: virtualbox
3962   │ DEBUG provider: Found cap: forwarded_ports in virtualbox
3963   │ DEBUG provider: Searching for cap: forwarded_ports
3964   │ DEBUG provider: Checking in: virtualbox
3965   │ DEBUG provider: Found cap: forwarded_ports in virtualbox
3966   │  INFO provider: Execute capability: forwarded_ports [#<Vagrant::Machine: DC01 (VagrantPlugins:
       │ :ProviderVirtualBox::Provider)>] (virtualbox)

```
```
 INFO interface: error: Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
 INFO interface: Machine: error-exit ["Vagrant::Errors::VMBootTimeout", "Timed out while waiting for the machine to boot. This means that\nVagrant was unable to communicate with the guest machine within\nthe configured (\"config.vm.boot_timeout\" value) time period.\n\nIf you look above, you should be able to see the error(s) that\nVagrant had when attempting to connect to the machine. These errors\nare usually good hints as to what may be wrong.\n\nIf you're using a custom box, make sure that networking is properly\nworking and you're able to connect to the machine. It is a common\nproblem that networking isn't setup properly in these boxes.\nVerify that authentication configurations are also setup properly,\nas well.\n\nIf the box appears to be booting properly, you may want to increase\nthe timeout (\"config.vm.boot_timeout\") value."]

```

Full debug output can be found at: https://paste.c-net.org/PlottingSlows

**Comment by grumo35** [comment] 2023-11-24 14:54
Hi,

From my point of view it looks like a network missconfiguration where your Vagrant host does not have network access to the vm you are trying to deploy.

**Comment by Mayfly277** [comment] 2023-11-25 20:46
seems to be a duplicate of this : https://github.com/Orange-Cyberdefense/GOAD/issues/129
please reopen if not

**Closed by Mayfly277** 2023-11-25 20:46 UTC

**Comment by PerennaSec** [comment] 2023-11-26 16:42
I encountered [#129](https://github.com/Orange-Cyberdefense/GOAD/issues/129) early on; however I have not found a way to apply the fix described within. That user was using WSL on a Windows host; I'm on a Gentoo Linux host. 

After doing some more reading I agree that this is most likely a network misconfiguration between the Vagrant host and the guest VM's. I confirmed there's no blocking on the part of my firewall or other host-based network protections. I wonder if hard-coding the VM IP addresses in the Vagrantfile via `config.winrm.host` would work? Maybe something like `config.winrm.host box[:ip]` ?  It seems to me that the remote shell should be opening in the `192.168.56.0/24` range, not on `127.0.0.1:55985` as shown above. I would assume that it's desired to use winrm to communicate with each host, however I'm unsure if adding a line like `config.winrm.host box[:ip]`  would further interfere with the setup.

Thank you both for your time, and suggestions! I deeply appreciate the help.

**Comment by Mayfly277** [comment] 2023-11-27 09:32
The ip as 127.0.0.1 is because vagrant automatically do a local port forwarding on creation.

can you give a try without ssl connection to vagrant see if it change something : 

add this lines in vagrantfile to not use ssl :
```
config.winrm.transport = "plaintext"
config.winrm.basic_auth_only = true
```

**Comment by PerennaSec** [comment] 2023-12-02 16:00
Thank you for the quick reply! The WinRM Authentication error persists. I've attached the full debug output below but the error message seems to be the same. 

https://paste.c-net.org/InsanityScrooge

**Comment by Mayfly277** [comment] 2024-03-25 16:53
you can try this : https://gist.github.com/JohnTroony/ab035f2bd1722de74bc36dd6619fa60c
